[package]
name = "marker"
version = "0.1.0"
authors = [
    "Fabio Colacio <fabio.colacio.dev@gmail.com>",
    "Martino Ferrari"
]

[dependencies]
gtk = "0.4.1"
gio = "0.4.1"
sourceview = "0.4.0"
webkit2gtk = "0.4.0"

